version: '3.8'
services:
    odoo:
        container_name: graphql_demo_odoo
        environment:
          - HOST=db
          - USER=odoo
          - PASSWORD=odoo
        build: .
        ports: ["8099:8069"]
        stdin_open: true
        tty: true
        user: odoo
        volumes:
          - odoo-web-data:/var/lib/odoo
          - ./extra-addons:/mnt/extra-addons
    db:
        container_name: graphql_demo_db
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_PASSWORD=odoo
          - POSTGRES_USER=odoo
          - PGDATA=/var/lib/postgresql/data/pgdata
        image: postgres:13-alpine
        ports: ["5435:5432"]
        volumes: 
          - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
    odoo-db-data:
    odoo-web-data: